### ISSUE TITLE
Timeouts are not honored on Metal resources/data sources

### ISSUE THREAD

**Issue by aayushrangwala** [equinix/terraform-provider-equinix#357]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version

`v1.5.4`

### Affected Resource(s)
- Metal Devices resource and datasource
- Metal ports
- Metal VRF
- Network Device
- SSH Key and a few more

### Terraform Configuration Files

```tf
resource "equinix_metal_device" "device" {
  hostname         = "tf-device"
  plan             = var.plan
  metro            = var.metro
  operating_system = var.os
  billing_cycle    = "hourly"
  project_id       = var.project_id
#
  depends_on = [ equinix_metal_project_ssh_key.public_key ]

  timeouts {
    create = "5s"
  }
}
```

### References
Some of the Metal resources/data sources (for example, the equinix_metal_device resource) indicate support for timeouts in their docs and schema, but do not actually support those timeouts.

Per terraform-plugin-sdk v2 docs, we should be using CreateContext, DeleteContext, etc. functions in order to have terraform automatically handle timeouts on our behalf: https://developer.hashicorp.com/terraform/plugin/sdkv2/guides/v2-upgrade-guide#more-support-for-context-context 

Also, for the resources and datasources when the `context aware` timeouts would not be suitable, use Hashicorp's [WaitForStateContext](https://github.com/hashicorp/terraform-plugin-sdk/blob/8bde488a9529d281bc6858ca2b0a3708c2f93658/helper/retry/state.go#L57)

We should find any Metal resources & data sources that have a Timeouts schema property and ensure that those resources & data sources use context-aware CRUD functions.

### Tasks

Upgrade resources and data sources to support context aware or without context CRUD timeouts

- [x] [DataSource and Resource Metal Device support](https://github.com/equinix/terraform-provider-equinix/pull/364)
- [ ] [DataSource and Resource Metal Port support](https://github.com/equinix/terraform-provider-equinix/pull/377)
- [ ] [DataSource and Resource Metal Sport Market Request support](https://github.com/equinix/terraform-provider-equinix/pull/379)
- [x] [DataSource and Resource Metal Virtual Circuit support](https://github.com/equinix/terraform-provider-equinix/pull/380)
- [ ] [DataSource and Resource Metal VRF support](https://github.com/equinix/terraform-provider-equinix/pull/386)
- [x] [Resource Metal Reserved IP Block support](https://github.com/equinix/terraform-provider-equinix/pull/388)
- [x] [Resource Network Device support](https://github.com/equinix/terraform-provider-equinix/pull/387)
